[package]
name = "door-driver"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ctrlc = "3.2.3"
evdev = "0.12.0"
xkbcommon = "0.5.0"

[[bin]]
name = "door-driver"
path = "main.rs"
